In [3]:
import cv2
mypath = "C:\\users\\sigma_db.tif"
img = cv2.imread(mypath,1)
print(img)
def wind(img):
    cv2.imshow('Sigma', img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
height, width = img.shape[0:2]
img.shape[0:2]
print(img.shape[0:2])
startRow = int(height*.10)
startCol = int(width*.10)
endRow = int(height*.99)
endCol = int(width*.90)
croppedImage = img[startRow:endRow, startCol:endCol]
cv2.imshow('Original Image', img)
cv2.imshow('Cropped Image', croppedImage)
cv2.waitKey(0)
newImg = cv2.resize(img, (0,2), fx=0.60, fy=0.65)
cv2.imshow('Resized Image', newImg)
cv2.waitKey(0)
edge_img = cv2.Canny(img,100,200) 
wind(edge_img)


[[[  1   1   1]
  [  1   1   1]
  [  1   1   1]
  ...
  [  1   1   1]
  [  1   1   1]
  [  1   1   1]]

 [[  1   1   1]
  [  1   1   1]
  [  1   1   1]
  ...
  [  1   1   1]
  [  1   1   1]
  [  1   1   1]]

 [[  1   1   1]
  [  1   1   1]
  [  1   1   1]
  ...
  [  1   1   1]
  [  1   1   1]
  [  1   1   1]]

 ...

 [[255 255 255]
  [255 255 255]
  [254 254 254]
  ...
  [  5   5   5]
  [  6   6   6]
  [  7   7   7]]

 [[255 255 255]
  [253 253 253]
  [253 253 253]
  ...
  [  4   4   4]
  [  5   5   5]
  [  6   6   6]]

 [[254 254 254]
  [255 255 255]
  [254 254 254]
  ...
  [  5   5   5]
  [  5   5   5]
  [  5   5   5]]]
(2121, 3359)


In [8]:
import numpy as np
import cv2
mypath ="C:\\users\\sigma_db.tif"
img = cv2.imread(mypath,1)
print(img)
p=cv2.imread(mypath, cv2.IMREAD_COLOR).dtype
print(p)
print(type(img))

[[[ 44  44  44]
  [ 46  46  46]
  [ 50  50  50]
  ...
  [ 18  18  18]
  [ 17  17  17]
  [ 17  17  17]]

 [[ 44  44  44]
  [ 51  51  51]
  [ 55  55  55]
  ...
  [ 18  18  18]
  [ 15  15  15]
  [ 20  20  20]]

 [[ 48  48  48]
  [ 50  50  50]
  [ 49  49  49]
  ...
  [ 20  20  20]
  [ 14  14  14]
  [ 18  18  18]]

 ...

 [[251 251 251]
  [255 255 255]
  [255 255 255]
  ...
  [ 42  42  42]
  [ 46  46  46]
  [ 47  47  47]]

 [[254 254 254]
  [255 255 255]
  [255 255 255]
  ...
  [ 45  45  45]
  [ 45  45  45]
  [ 46  46  46]]

 [[254 254 254]
  [255 255 255]
  [255 255 255]
  ...
  [ 51  51  51]
  [ 55  55  55]
  [ 52  52  52]]]
uint8
<class 'numpy.ndarray'>


In [19]:
import cv2
import numpy as np
from skimage.util import img_as_float
mypath="C:\\users\\Sigma0_HH.tif"
image = cv2.imread(mypath,1)
imag = img_as_float(image)
#print(imag)
p=cv2.imread(mypath, cv2.IMREAD_COLOR).dtype
#print(p)
print(imag[20, 102])
#print(type(img))

[0.00392157 0.00392157 0.00392157]


In [2]:
import numpy as np
import cv2
from matplotlib import pyplot as plt
mypath = "C:\\Users\\TC_Spk_Sigma0_HH.tif"
lena=cv2.imread(mypath,0)
print(lena)
hist=cv2.calcHist([lena],[0],None,[256],[0,256])                  #histogram of image
xaxis=np.arange(256).reshape(256,1)                                              
histogram=np.hstack((xaxis,hist)).astype(int)
plt.hist(lena.flatten(),256,[0,256])
plt.show

None


AttributeError: 'NoneType' object has no attribute 'flatten'

In [21]:
import numpy as np
import cv2
from matplotlib import pyplot as plt
mypath = "C:\\Users\\sigma_db.tif"
img=cv2.imread(mypath,0)
imgCL=np.float32(img.reshape((-1,3)))
cr=(cv2.TERM_CRITERIA_EPS+cv2.TERM_CRITERIA_MAX_ITER,15,1.0)
k=4
ret,lab,center=cv2.kmeans(imgCL,k,None,cr,10,cv2.KMEANS_RANDOM_CENTERS)
ret

2571284667.2392187

In [23]:
lab

array([[2],
       [2],
       [2],
       ...,
       [2],
       [2],
       [2]], dtype=int32)